name: CI
on:
  pull_request:

permissions:
  contents: read

jobs:
  verify_changes:
    name: Verify changes
    concurrency:
      group: verify_changes_group_${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.verify_changed_files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: verify_changed_files
        name: Check changes golang and workflow files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          files: |
            **.go
            .github/workflows/**

      - name: List all changed files
        if: steps.verify_changed_files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.verify_changed_files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  vendor:
    if: needs.verify_changes.outputs.changed == 'true'
    name: Go vendor
    needs: [verify_changes]
    concurrency:
      group: vendor_group_${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - run: go mod vendor
      - uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor


  lint:
    name: Run linters
    needs: [vendor]
    concurrency:
      group: lint_group_${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: vendor
      - run: apt-get -y install make
      - run: make lint

  test_and_coverage:
    name: Run unit tests & check coverage
    needs: [vendor]
    concurrency:
      group: test_group_${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt -y install make
      - run: apt -y install bc
      - uses: actions/download-artifact@v4
        name: vendor
      - name: Run test
        run: make test
      - name: Current coverage
        run: make cov
      - name: Check test coverage
        run: make check-cov

