name: CI
on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3

  test:
    runs-on: ubuntu-latest
    container: golang:1.22-alpine
    name: unit tests
    steps:
      - run: make test

  check_coverage:
    runs-on: ubuntu-latest
    container: golang:1.22-alpine
    name: check test coverage
    steps:
      - run: make check-cov