name: CI
on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - run: apt-get -y install make
      - run: make lint

  test_and_coverage:
    name: Run unit tests & check coverage
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt -y install make
      - run: apt -y install bc
      - name: Run test
        run: make test
      - name: Current coverage
        shell: bash
        run: make cov
      - name: Check test coverage
        shell: bash
        run: make check-cov

