name: CI
on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - run: apt-get -y install make
      - run: make lint

  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    name: unit tests
    steps:
      - uses: actions/checkout@v4
      - run: apt -y install make
      - run: make test

  check_coverage:
    runs-on: ubuntu-latest
    container: golang:1.22
    name: check test coverage
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt -y install make
      - run: apt -y install bc
      - run: make check-cov